# Name: Allen Chin
# Course: CS178 Build Automation for DevOps and QA
# CRN: 76718
# Date: 09/01/2019
# Assignment: Asterisks

# Variables
CXX = g++
CXXFLAGS = -Wall -g

HelloWorld: HelloWorld.cpp
	$(CXX) $(CXXFLAGS) -o HelloWorld HelloWorld.cpp

clean:
	rm -f HelloWorld